#include "Stages/input_manipulation.h"
#include "Stages/exec.h"
#include "Stages/directory_path_manipulation.h"
#include "Stages/changing_dir.h"
#include "Stages/history.h"
#include "Stages/linked_list.h"
#include "Stages/file_handling.h"
#include "Stages/alias.h"