#include "Stages/input_manipulation.h"
#include "Stages/stage_2.h"
#include "Stages/stage_3.h"
#include "Stages/stage_4.h"
#include "Stages/history.h"
#include "Stages/linked_list.h"
#include "Stages/file_handling.h"
#include "Stages/alias.h"